use core::{
    fmt::{self, Display, Formatter},
    str::FromStr,
    time::Duration,
};

use lb_ledger::mantle::sdp::rewards::blend::RewardsParameters;
use lb_utils::yaml::{OnUnknownKeys, deserialize_value_from_reader};
use serde::{Deserialize, Serialize};

use crate::config::{
    blend::deployment::Settings as BlendDeploymentSettings,
    cryptarchia::deployment::Settings as CryptarchiaDeploymentSettings,
    mempool::deployment::Settings as MempoolDeploymentSettings,
    network::deployment::Settings as NetworkDeploymentSettings,
    time::deployment::Settings as TimeDeploymentSettings,
};

pub mod builtin;

/// The single deployment embedded in the binary at compile time.
///
/// "Well-known" means "the deployment baked into this binary", not a specific
/// network tier. The actual network identity (devnet/testnet/standalone) lives
/// in the embedded content's protocol namespace, generated by the genesis
/// ceremony for whatever tier the release branch targets. The binary never
/// asserts a tier, so it can never lie about which network it embeds.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, Default)]
pub enum WellKnownDeployment {
    // Must match the `NAME` definition in the `builtin` module.
    #[serde(rename = "builtin")]
    #[default]
    Builtin,
}

impl FromStr for WellKnownDeployment {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            builtin::NAME => Ok(Self::Builtin),
            _ => Err(()),
        }
    }
}

impl Display for WellKnownDeployment {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::Builtin => write!(f, "{}", builtin::NAME),
        }
    }
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct DeploymentSettings {
    pub blend: BlendDeploymentSettings,
    pub network: NetworkDeploymentSettings,
    pub cryptarchia: CryptarchiaDeploymentSettings,
    pub time: TimeDeploymentSettings,
    pub mempool: MempoolDeploymentSettings,
}

impl From<WellKnownDeployment> for DeploymentSettings {
    fn from(value: WellKnownDeployment) -> Self {
        match value {
            WellKnownDeployment::Builtin => {
                deserialize_value_from_reader(builtin::SERIALIZED_DEPLOYMENT, OnUnknownKeys::Fail)
                    .expect("Built-in deployment config is valid.")
            }
        }
    }
}

impl DeploymentSettings {
    #[must_use]
    pub const fn blend_round_duration(&self) -> Duration {
        self.blend.round_duration(&self.time.slot_duration)
    }

    #[must_use]
    pub fn blend_reward_params(&self) -> RewardsParameters {
        self.blend.rewards_params(&self.cryptarchia, &self.time)
    }
}

#[cfg(test)]
mod tests {
    use crate::config::{DeploymentSettings, WellKnownDeployment};

    #[test]
    fn builtin_initialization() {
        drop(DeploymentSettings::from(WellKnownDeployment::Builtin));
    }

    #[test]
    fn serialize_deserialize_yaml() {
        let settings = DeploymentSettings::from(WellKnownDeployment::Builtin);
        let as_str = serde_yaml::to_string(&settings).unwrap();
        let _recovered: DeploymentSettings = serde_yaml::from_str(&as_str).unwrap();
    }
}
