[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "logos-blockchain-blend-primitives"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
tokio   = { workspace = true }

[dev-dependencies]
tokio = { features = ["macros", "test-util"], workspace = true }
