[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "logos-blockchain-cryptarchia-engine"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[package.metadata.cargo-machete]
# False positives.
ignored = ["logos-blockchain-utils"]

[lints]
workspace = true

[dependencies]
lb-log-targets = { workspace = true }
lb-pol         = { workspace = true }
lb-time        = { workspace = true }
lb-utils       = { workspace = true }
rpds           = { workspace = true }
serde          = { workspace = true }
thiserror      = { workspace = true }
time           = { workspace = true }
tokio          = { features = ["time"], optional = true, workspace = true }
tracing        = { workspace = true }
utoipa         = { features = ["macros"], optional = true, workspace = true }

[features]
openapi = ["dep:utoipa", "lb-time/openapi"]
tokio   = ["dep:tokio"]
