[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "logos-blockchain-zksign"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[dependencies]
logos-blockchain-circuits-prover   = { workspace = true }
logos-blockchain-circuits-utils    = { workspace = true }
logos-blockchain-groth16           = { features = ["deser"], workspace = true }
logos-blockchain-poseidon2         = { workspace = true }
logos-blockchain-witness-generator = { workspace = true }
num-bigint                         = { default-features = false, version = "0.4" }
serde                              = { features = ["derive"], workspace = true }
serde_json                         = { workspace = true }
thiserror                          = { workspace = true }

[dev-dependencies]
logos-blockchain-poseidon2 = { workspace = true }
num-bigint                 = "0.4"
rand                       = "0.8"

[build-dependencies]
logos-blockchain-circuits-utils = { workspace = true }

[lints]
workspace = true

[features]
build-verification-key = []
default                = ["build-verification-key"]
