{
 "title": "Testnet Metrics",
 "tags": [
  "testnet",
  "metrics",
  "legacy",
  "per-metric"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "blend_inbound_messages_failed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(blend_inbound_messages_failed_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "blend_messages_received_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(blend_messages_received_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "blend_messages_sent_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(blend_messages_sent_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "blend_mix_packets_processed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(blend_mix_packets_processed_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "blend_outbound_messages_failed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(blend_outbound_messages_failed_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "blend_peers_connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "blend_peers_connected",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "chainsync_download_blocks_blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(chainsync_download_blocks_blocks_count[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "chainsync_download_blocks_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(chainsync_download_blocks_seconds_count[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "chainsync_request_tip_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "increase(chainsync_request_tip_seconds_count[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "chainsync_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "increase(chainsync_requests_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_apply_block_failed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "increase(consensus_apply_block_failed_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_apply_block_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "increase(consensus_apply_block_seconds_count[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_block_blob_validation_failed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "increase(consensus_block_blob_validation_failed_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_block_blob_validation_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "increase(consensus_block_blob_validation_seconds_count[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_block_transactions_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "increase(consensus_block_transactions_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_blocks_imported_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "increase(consensus_blocks_imported_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "consensus_connections",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_current_epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "consensus_current_epoch",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_current_slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "consensus_current_slot",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_finalized_height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "consensus_finalized_height",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_forks_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "consensus_forks_count",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_peers_connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "consensus_peers_connected",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_proposal_missing_txs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "increase(consensus_proposal_missing_txs_count[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_proposal_reconstruct_failed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "increase(consensus_proposal_reconstruct_failed_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_proposal_reconstruct_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "increase(consensus_proposal_reconstruct_seconds_count[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_proposals_create_failed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "increase(consensus_proposals_create_failed_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_proposals_created_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "increase(consensus_proposals_created_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_proposals_ignored_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "increase(consensus_proposals_ignored_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_proposals_received_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "increase(consensus_proposals_received_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "consensus_tip_height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "expr": "consensus_tip_height",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "http_request_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_count[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "http_requests_failed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "expr": "increase(http_requests_failed_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "http_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "increase(http_requests_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "kms_execute_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "targets": [
    {
     "expr": "increase(kms_execute_failures_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "kms_execute_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": "increase(kms_execute_requests_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "kms_public_key_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "targets": [
    {
     "expr": "increase(kms_public_key_requests_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "kms_register_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "targets": [
    {
     "expr": "increase(kms_register_failures_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "kms_register_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "targets": [
    {
     "expr": "increase(kms_register_requests_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "kms_register_success_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "targets": [
    {
     "expr": "increase(kms_register_success_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "kms_sign_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "targets": [
    {
     "expr": "increase(kms_sign_failures_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "kms_sign_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "targets": [
    {
     "expr": "increase(kms_sign_requests_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "kms_sign_success_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "targets": [
    {
     "expr": "increase(kms_sign_success_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "mempool_transactions_added_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "targets": [
    {
     "expr": "increase(mempool_transactions_added_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "mempool_transactions_pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "targets": [
    {
     "expr": "mempool_transactions_pending",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "mempool_transactions_removed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "targets": [
    {
     "expr": "increase(mempool_transactions_removed_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "network_dial_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "targets": [
    {
     "expr": "increase(network_dial_failures_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "orphan_blocks_enqueued_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "targets": [
    {
     "expr": "increase(orphan_blocks_enqueued_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "orphan_blocks_fetch_failed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "targets": [
    {
     "expr": "increase(orphan_blocks_fetch_failed_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "orphan_blocks_parent_fetch_failed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "targets": [
    {
     "expr": "increase(orphan_blocks_parent_fetch_failed_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "orphan_blocks_parent_fetch_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "targets": [
    {
     "expr": "increase(orphan_blocks_parent_fetch_seconds_count[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "orphan_blocks_pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "targets": [
    {
     "expr": "orphan_blocks_pending",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "orphan_blocks_queue_full_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "targets": [
    {
     "expr": "increase(orphan_blocks_queue_full_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "orphan_blocks_received_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "targets": [
    {
     "expr": "increase(orphan_blocks_received_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "orphan_blocks_removed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
   "targets": [
    {
     "expr": "increase(orphan_blocks_removed_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_activity_mempool_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
   "targets": [
    {
     "expr": "increase(sdp_activity_mempool_failures_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_activity_posts_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
   "targets": [
    {
     "expr": "increase(sdp_activity_posts_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_activity_success_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
   "targets": [
    {
     "expr": "increase(sdp_activity_success_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_activity_tx_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 224 },
   "targets": [
    {
     "expr": "increase(sdp_activity_tx_failures_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_declaration_mempool_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 232 },
   "targets": [
    {
     "expr": "increase(sdp_declaration_mempool_failures_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_declaration_success_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 232 },
   "targets": [
    {
     "expr": "increase(sdp_declaration_success_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_declaration_tx_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 240 },
   "targets": [
    {
     "expr": "increase(sdp_declaration_tx_failures_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_declarations_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 240 },
   "targets": [
    {
     "expr": "increase(sdp_declarations_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_subscription_errors_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 248 },
   "targets": [
    {
     "expr": "increase(sdp_subscription_errors_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_subscriptions_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 248 },
   "targets": [
    {
     "expr": "increase(sdp_subscriptions_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_withdrawal_mempool_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 256 },
   "targets": [
    {
     "expr": "increase(sdp_withdrawal_mempool_failures_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_withdrawal_success_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 256 },
   "targets": [
    {
     "expr": "increase(sdp_withdrawal_success_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_withdrawal_tx_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 264 },
   "targets": [
    {
     "expr": "increase(sdp_withdrawal_tx_failures_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_withdrawal_validation_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 264 },
   "targets": [
    {
     "expr": "increase(sdp_withdrawal_validation_failures_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "sdp_withdrawals_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 272 },
   "targets": [
    {
     "expr": "increase(sdp_withdrawals_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "storage_request_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 272 },
   "targets": [
    {
     "expr": "increase(storage_request_duration_seconds_count[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "storage_request_failed_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 280 },
   "targets": [
    {
     "expr": "increase(storage_request_failed_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "time_broadcast_errors_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 280 },
   "targets": [
    {
     "expr": "increase(time_broadcast_errors_total[$__range])",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "time_current_epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 288 },
   "targets": [
    {
     "expr": "time_current_epoch",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  },
  {
   "title": "time_current_slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 288 },
   "targets": [
    {
     "expr": "time_current_slot",
     "legendFormat": "{{service_name}} {{instance}} {{action}} {{origin}} {{reason}} {{kind}} {{result}} {{method}} {{endpoint}} {{status}} {{status_class}} {{mode}} {{strategy}} {{message_type}}"
    }
   ]
  }
 ]
}