[package]
categories  = { workspace = true }
description = "Logos SQL (λSQL) - decentralized SQLite over Logos Blockchain"
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "logos-sql"
publish     = false
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[lints]
workspace = true

[dependencies]
bincode                          = { workspace = true }
lb-key-management-system-service = { workspace = true }
lb-log-targets                   = { workspace = true }
lb-zone-sdk                      = { workspace = true }
rand                             = { features = ["getrandom"], workspace = true }
reqwest                          = { workspace = true }
rusqlite                         = { features = ["bundled", "functions", "hooks"], workspace = true }
serde                            = { features = ["derive"], workspace = true }
thiserror                        = { workspace = true }
tokio                            = { features = ["macros", "rt", "sync", "time"], workspace = true }
tracing                          = { workspace = true }

[dev-dependencies]
clap       = { features = ["derive", "env", "help", "std"], workspace = true }
hex        = { workspace = true }
lb-groth16 = { workspace = true }
tempfile   = { workspace = true }
