[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "logos-blockchain-blend-service"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[lints]
workspace = true

[dependencies]
async-trait                                    = "0.1"
fork_stream                                    = { workspace = true }
futures                                        = { default-features = false, version = "0.3" }
libp2p                                         = { optional = true, workspace = true }
libp2p-stream                                  = { optional = true, workspace = true }
logos-blockchain-blend                         = { workspace = true }
logos-blockchain-chain-broadcast-service       = { workspace = true }
logos-blockchain-chain-service                 = { workspace = true }
logos-blockchain-core                          = { workspace = true }
logos-blockchain-cryptarchia-engine            = { workspace = true }
logos-blockchain-groth16                       = { default-features = false, workspace = true }
logos-blockchain-key-management-system-service = { workspace = true }
logos-blockchain-ledger                        = { workspace = true }
logos-blockchain-libp2p                        = { optional = true, workspace = true }
logos-blockchain-network-service               = { workspace = true }
logos-blockchain-poq                           = { workspace = true }
logos-blockchain-sdp-service                   = { workspace = true }
logos-blockchain-services-utils                = { workspace = true }
logos-blockchain-time-service                  = { workspace = true }
logos-blockchain-utils                         = { features = ["serde"], workspace = true }
overwatch                                      = { workspace = true }
rand                                           = { workspace = true }
serde                                          = { workspace = true }
serde_with                                     = { workspace = true }
thiserror                                      = { default-features = false, version = "1" }
tokio                                          = { default-features = false, version = "1" }
tokio-stream                                   = { default-features = false, version = "0.1" }
tracing                                        = { workspace = true }

[dev-dependencies]
libp2p                 = { default-features = false, features = ["plaintext", "tcp", "yamux"], workspace = true }
libp2p-swarm-test      = { default-features = false, version = "0.5.0" }
logos-blockchain-blend = { features = ["unsafe-test-functions"], workspace = true }
tempfile               = { workspace = true }
test-log               = { default-features = false, version = "0.2.18", features = ["trace"] }

[features]
default = []
libp2p  = ["dep:libp2p", "dep:libp2p-stream", "dep:logos-blockchain-libp2p", "logos-blockchain-network-service/libp2p"]
