[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "logos-blockchain-groth16"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[dependencies]
ark-bn254     = { workspace = true, features = ["curve"] }
ark-ec        = { workspace = true }
ark-ff        = { workspace = true }
ark-groth16   = { workspace = true, features = ["std"] }
ark-serialize = { workspace = true }
generic-array = { workspace = true, features = ["serde"] }
hex           = { workspace = true, features = ["alloc"] }
num-bigint    = { workspace = true }
serde         = { features = ["derive"], workspace = true }
serde_json    = { workspace = true, features = ["alloc"] }
thiserror     = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }

[lints]
workspace = true
