//! `λSQL`: replicated `SQLite` state over Logos Blockchain.
//!
//! Applications read through a normal `SQLite` connection and submit replicated
//! writes through [`LogosSql::execute`]. One dedicated runtime thread owns the
//! zone sequencer and database writer, so the SQL effects and pending
//! publication commit together before the payload is given to `ZoneSDK`.
//!
//! Application transactions share a fixed SQLite execution budget across their
//! statements. Exceeding it rolls back the transaction; channel replay records
//! the rejection and continues. SQL text, individual values and complete rows
//! are limited to 64 MiB, including values generated by SQL functions. These
//! limits are not a wall-clock timeout or a total memory/disk quota.

mod applier;
mod db;
mod error;
mod functions;
mod logos_sql;
mod protocol;
mod publication;
mod runtime;
mod sql;
mod status;

pub use error::Error;
pub use logos_sql::{LogosSql, LogosSqlConfig, PublicationConfig, WriterConfig};
pub use protocol::TxId;
pub use rusqlite::types::ToSql;
pub use sql::TransactionBuilder;
pub use status::{Displacement, DisplacementReason, WriteStatus};
