[package]
categories.workspace  = true
description.workspace = true
edition.workspace     = true
keywords.workspace    = true
license.workspace     = true
name                  = "logos-blockchain-faucet"
readme.workspace      = true
repository.workspace  = true
version.workspace     = true

[dependencies]
axum                          = { workspace = true, features = ["http1", "http2", "json", "tokio"] }
clap                          = { workspace = true, features = ["derive", "env", "std"] }
hex                           = { workspace = true, features = ["alloc"] }
lb-common-http-client         = { workspace = true }
lb-groth16                    = { workspace = true }
lb-http-api-common            = { workspace = true }
lb-key-management-system-keys = { workspace = true }
lb-node                       = { workspace = true }
reqwest                       = { workspace = true }
serde_yaml                    = { workspace = true }
tokio                         = { features = ["macros", "net", "rt-multi-thread"], workspace = true }

[lints]
workspace = true

[[bin]]
name = "logos-blockchain-faucet"
path = "src/bin/faucet.rs"
