blend:
  common:
    num_blend_layers: 1
    minimum_network_size: 32
    protocol_name: /logos-blockchain-devnet/blend/1.0.0
    data_replication_factor: 0
  core:
    scheduler:
      cover:
        message_frequency_per_round: 1.0
        intervals_for_safety_buffer: 100
      delayer:
        maximum_release_delay_in_rounds: 1
    minimum_messages_coefficient: 1
    normalization_constant: 1.03
    activity_threshold_sensitivity: 1
network:
  kademlia_protocol_name: /logos-blockchain-devnet/kad/1.0.0
  identify_protocol_name: /logos-blockchain-devnet/identify/1.0.0
  chain_sync_protocol_name: /logos-blockchain-devnet/chainsync/1.0.0
cryptarchia:
  epoch_config:
    epoch_stake_distribution_stabilization: 3
    epoch_period_nonce_buffer: 3
    epoch_period_nonce_stabilization: 4
  security_param: 30
  slot_activation_coeff:
    numerator: 1
    denominator: 20
  learning_rate: 0.5
  sdp_config:
    service_params:
      BN:
        lock_period: 10
        inactivity_period: 1
        retention_period: 1
        timestamp: 0
    min_stake:
      threshold: 1
      timestamp: 0
  gossipsub_protocol: /logos-blockchain-devnet/cryptarchia/1.0.0
  genesis_state:
    mantle_tx:
      ops:
      - opcode: 0
        payload:
          inputs: []
          outputs:
          - value: 100000
            pk: 023301b903fa7173637dffe490d643aa5fd7c6ad42e696253a91921b5f93b11e
          - value: 1
            pk: 95182026c229fa03adb5bbacd859c3e512f34284ef1db8100b272159eb557029
          - value: 100
            pk: 57fd3cf9abdcc87ee95a951f0ebb3604cd4dd787d74de844e7adf686099eee15
          - value: 100000
            pk: b1299b28da709a5a422fd9157bfbe0924031a509d440c102b7d44dd46302f40a
          - value: 1
            pk: 9574ac2426e666177653ed54f14ca8d4e09e6ccc386a503dc6da4e090c4f7d1d
          - value: 100
            pk: cbc8cb3fcef3b77fe5569da6b98ac39ed2fceebc27871879268e303cb854ad0a
          - value: 100000
            pk: 4acffec29e556d862d1dada437616e1da81b8e9961b75fe43c2759682477400d
          - value: 1
            pk: 4b8cce7433aa3e2ba7e7896aefb929f2ae5b5686452aa39a029187f63c6d2314
          - value: 100
            pk: 77a4f68356b3849998966742c179acccc2e25c74958756c95680bc2951a9c310
          - value: 100000
            pk: 799352fec1bb5d32de7f3e3e89d01abc771a1a684eaf1f9bda7dfdf672fcec03
          - value: 1
            pk: 616653275260697c5e7b488b566977e181b1441f06c60fc630efdd17fb756424
          - value: 100
            pk: 9afff465c819ce3510b3db3c0cbee7fad168e7f94433813e8d5b452b75af441c
          - value: 18446744073709151211
            pk: d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916
      - opcode: 17
        payload:
          channel_id: '0000000000000000000000000000000000000000000000000000000000000000'
          inscription:
          - 112
          - 114
          - 111
          - 99
          - 101
          - 115
          - 115
          - 95
          - 115
          - 116
          - 97
          - 114
          - 116
          - 95
          - 110
          - 111
          - 110
          - 99
          - 101
          - 61
          - 49
          - 56
          - 97
          - 54
          - 97
          - 50
          - 101
          - 97
          - 51
          - 99
          - 99
          - 102
          - 98
          - 54
          - 97
          - 48
          - 45
          - 48
          - 48
          - 48
          - 49
          - 54
          - 54
          - 53
          - 49
          - 44
          - 32
          - 116
          - 101
          - 115
          - 116
          - 95
          - 101
          - 110
          - 116
          - 114
          - 111
          - 112
          - 121
          - 61
          - 54
          - 49
          - 52
          - 52
          - 56
          - 97
          - 51
          - 98
          - 55
          - 57
          - 99
          - 102
          - 52
          - 50
          - 97
          - 49
          parent: '0000000000000000000000000000000000000000000000000000000000000000'
          signer: '0000000000000000000000000000000000000000000000000000000000000000'
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /ip4/127.0.0.0/udp/3400/quic-v1
          provider_id: 4cb4cab9cdc46dd5a7ad3966570505ba5c61aa943a763632b632e14c93aeefb3
          zk_id: efaebbcee3b487cf152cc20625e0c1fe61667113914323793a3e99bf54e1d80c
          locked_note_id: 688aced4612f0b1d0181e035c257406714479423b24ab0994ecc549a07f5ab29
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /ip4/127.0.0.1/udp/3400/quic-v1
          provider_id: 168773da0fcf68c7921657ad4158cc24fb18fe98dc07e66e03422fbae3d63f16
          zk_id: efb0644826540fb81383e488f3b3de1a885bcb545a61743bbcccdf02df7a162b
          locked_note_id: cd56077e84d3b2ca0a0a93b2146454fb9b13857187333a8c7cb60da35dc1c524
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /ip4/127.0.0.2/udp/3400/quic-v1
          provider_id: 395a43ff4d805c8f25d154dee2f5526e85be6352b5436e3689d9092fd1f346d7
          zk_id: 2285537a2ab31794caa54193eb845269722e394bb0255e5b836705a2690c3b0f
          locked_note_id: 567a6f63251c805290520b4c08ef468b346035c61f11d6c8979b14273e51d700
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /ip4/127.0.0.3/udp/3400/quic-v1
          provider_id: a11d39b038b61382db01a72f5a5c34a3f2cfe775857eba7e68e069dbb7db0bf1
          zk_id: 782ba296b82086fa8f221d40c5471cf2563edbda1345fa259a04ee478bf0701f
          locked_note_id: 7e0d7f22703997e338a1b5c4a69c9085ef6f9e7f087755f81274ec8c734a2713
      execution_gas_price: 0
      storage_gas_price: 0
    ops_proofs:
    - !ZkSig
      pi_a:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      pi_b:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      pi_c:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    - NoProof
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 4
        - 58
        - 225
        - 30
        - 222
        - 188
        - 230
        - 62
        - 218
        - 189
        - 18
        - 2
        - 86
        - 36
        - 141
        - 109
        - 245
        - 142
        - 31
        - 71
        - 80
        - 38
        - 211
        - 225
        - 121
        - 183
        - 94
        - 24
        - 103
        - 202
        - 55
        - 47
        pi_b:
        - 66
        - 39
        - 178
        - 249
        - 93
        - 18
        - 121
        - 107
        - 116
        - 170
        - 33
        - 7
        - 216
        - 177
        - 18
        - 33
        - 103
        - 244
        - 154
        - 1
        - 191
        - 71
        - 164
        - 255
        - 216
        - 63
        - 34
        - 150
        - 152
        - 197
        - 226
        - 9
        - 160
        - 113
        - 172
        - 100
        - 113
        - 133
        - 40
        - 93
        - 139
        - 39
        - 97
        - 223
        - 44
        - 143
        - 209
        - 223
        - 20
        - 176
        - 227
        - 116
        - 6
        - 72
        - 160
        - 75
        - 75
        - 227
        - 112
        - 5
        - 195
        - 61
        - 55
        - 27
        pi_c:
        - 43
        - 27
        - 48
        - 117
        - 72
        - 30
        - 107
        - 6
        - 246
        - 150
        - 165
        - 29
        - 27
        - 196
        - 40
        - 193
        - 223
        - 215
        - 18
        - 34
        - 25
        - 193
        - 146
        - 138
        - 157
        - 88
        - 12
        - 114
        - 29
        - 19
        - 247
        - 41
      ed25519_sig:
      - 190
      - 120
      - 145
      - 20
      - 225
      - 224
      - 121
      - 213
      - 93
      - 3
      - 132
      - 110
      - 148
      - 80
      - 228
      - 73
      - 36
      - 219
      - 89
      - 183
      - 179
      - 118
      - 208
      - 212
      - 201
      - 167
      - 139
      - 49
      - 66
      - 230
      - 147
      - 238
      - 124
      - 67
      - 198
      - 229
      - 241
      - 11
      - 220
      - 223
      - 162
      - 31
      - 41
      - 80
      - 33
      - 35
      - 108
      - 3
      - 4
      - 62
      - 93
      - 107
      - 162
      - 215
      - 167
      - 108
      - 72
      - 138
      - 83
      - 188
      - 237
      - 82
      - 114
      - 11
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 88
        - 95
        - 86
        - 159
        - 128
        - 116
        - 19
        - 248
        - 161
        - 54
        - 110
        - 132
        - 90
        - 8
        - 141
        - 37
        - 27
        - 215
        - 168
        - 38
        - 37
        - 146
        - 52
        - 5
        - 203
        - 145
        - 49
        - 62
        - 197
        - 226
        - 187
        - 135
        pi_b:
        - 249
        - 183
        - 109
        - 54
        - 57
        - 228
        - 44
        - 200
        - 179
        - 91
        - 79
        - 47
        - 74
        - 68
        - 81
        - 83
        - 30
        - 17
        - 73
        - 151
        - 6
        - 195
        - 53
        - 209
        - 254
        - 225
        - 89
        - 12
        - 12
        - 46
        - 229
        - 14
        - 34
        - 117
        - 29
        - 123
        - 100
        - 8
        - 33
        - 81
        - 194
        - 240
        - 192
        - 23
        - 144
        - 158
        - 187
        - 10
        - 155
        - 225
        - 250
        - 123
        - 66
        - 15
        - 252
        - 195
        - 5
        - 73
        - 70
        - 97
        - 55
        - 58
        - 249
        - 0
        pi_c:
        - 176
        - 252
        - 92
        - 74
        - 251
        - 186
        - 146
        - 201
        - 157
        - 165
        - 213
        - 133
        - 231
        - 163
        - 120
        - 127
        - 106
        - 168
        - 239
        - 25
        - 44
        - 159
        - 225
        - 226
        - 171
        - 0
        - 73
        - 183
        - 139
        - 159
        - 202
        - 142
      ed25519_sig:
      - 167
      - 222
      - 172
      - 91
      - 239
      - 215
      - 79
      - 250
      - 52
      - 26
      - 66
      - 184
      - 139
      - 62
      - 141
      - 208
      - 124
      - 147
      - 4
      - 31
      - 71
      - 242
      - 130
      - 254
      - 180
      - 135
      - 97
      - 10
      - 21
      - 235
      - 207
      - 218
      - 95
      - 205
      - 204
      - 182
      - 220
      - 131
      - 192
      - 84
      - 162
      - 62
      - 140
      - 203
      - 72
      - 6
      - 203
      - 215
      - 173
      - 60
      - 16
      - 195
      - 11
      - 140
      - 114
      - 126
      - 58
      - 219
      - 73
      - 103
      - 231
      - 239
      - 220
      - 15
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 70
        - 124
        - 240
        - 145
        - 223
        - 182
        - 124
        - 134
        - 132
        - 52
        - 172
        - 105
        - 7
        - 11
        - 182
        - 184
        - 186
        - 118
        - 224
        - 253
        - 40
        - 87
        - 241
        - 54
        - 75
        - 195
        - 24
        - 231
        - 217
        - 11
        - 240
        - 150
        pi_b:
        - 173
        - 110
        - 227
        - 139
        - 169
        - 93
        - 148
        - 199
        - 162
        - 74
        - 55
        - 16
        - 108
        - 52
        - 227
        - 252
        - 152
        - 5
        - 66
        - 29
        - 114
        - 55
        - 110
        - 199
        - 146
        - 152
        - 175
        - 158
        - 171
        - 151
        - 60
        - 10
        - 27
        - 122
        - 149
        - 147
        - 248
        - 66
        - 82
        - 240
        - 128
        - 186
        - 84
        - 218
        - 5
        - 33
        - 164
        - 215
        - 147
        - 108
        - 173
        - 142
        - 197
        - 162
        - 79
        - 250
        - 161
        - 206
        - 6
        - 118
        - 204
        - 66
        - 192
        - 153
        pi_c:
        - 21
        - 18
        - 165
        - 63
        - 237
        - 195
        - 66
        - 206
        - 158
        - 213
        - 66
        - 150
        - 139
        - 11
        - 179
        - 36
        - 85
        - 186
        - 252
        - 255
        - 80
        - 85
        - 240
        - 206
        - 91
        - 242
        - 147
        - 203
        - 108
        - 157
        - 18
        - 147
      ed25519_sig:
      - 170
      - 8
      - 93
      - 113
      - 53
      - 84
      - 43
      - 50
      - 129
      - 109
      - 159
      - 205
      - 147
      - 53
      - 23
      - 67
      - 146
      - 110
      - 153
      - 24
      - 195
      - 193
      - 58
      - 155
      - 78
      - 9
      - 199
      - 79
      - 134
      - 149
      - 160
      - 65
      - 252
      - 128
      - 237
      - 222
      - 71
      - 9
      - 139
      - 153
      - 144
      - 91
      - 229
      - 177
      - 110
      - 72
      - 1
      - 124
      - 197
      - 25
      - 25
      - 5
      - 61
      - 169
      - 125
      - 76
      - 214
      - 210
      - 40
      - 207
      - 28
      - 2
      - 192
      - 14
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 5
        - 1
        - 166
        - 179
        - 100
        - 24
        - 65
        - 50
        - 12
        - 105
        - 143
        - 73
        - 90
        - 108
        - 210
        - 130
        - 154
        - 129
        - 167
        - 232
        - 59
        - 203
        - 114
        - 247
        - 81
        - 83
        - 172
        - 2
        - 155
        - 71
        - 93
        - 15
        pi_b:
        - 89
        - 111
        - 145
        - 94
        - 43
        - 120
        - 14
        - 143
        - 98
        - 180
        - 157
        - 147
        - 83
        - 208
        - 145
        - 24
        - 201
        - 70
        - 239
        - 111
        - 194
        - 23
        - 216
        - 146
        - 95
        - 13
        - 167
        - 152
        - 242
        - 57
        - 199
        - 34
        - 92
        - 127
        - 205
        - 15
        - 32
        - 161
        - 121
        - 73
        - 199
        - 118
        - 96
        - 194
        - 29
        - 219
        - 211
        - 120
        - 87
        - 143
        - 2
        - 48
        - 91
        - 223
        - 205
        - 106
        - 146
        - 192
        - 164
        - 125
        - 158
        - 128
        - 99
        - 157
        pi_c:
        - 43
        - 137
        - 184
        - 223
        - 46
        - 88
        - 250
        - 125
        - 240
        - 6
        - 72
        - 35
        - 211
        - 225
        - 133
        - 93
        - 41
        - 52
        - 209
        - 239
        - 94
        - 254
        - 102
        - 121
        - 66
        - 240
        - 229
        - 153
        - 212
        - 115
        - 222
        - 129
      ed25519_sig:
      - 215
      - 106
      - 104
      - 143
      - 28
      - 157
      - 202
      - 104
      - 173
      - 66
      - 142
      - 221
      - 211
      - 233
      - 133
      - 198
      - 253
      - 162
      - 144
      - 152
      - 240
      - 148
      - 93
      - 181
      - 83
      - 144
      - 104
      - 84
      - 227
      - 153
      - 35
      - 45
      - 175
      - 25
      - 255
      - 213
      - 145
      - 87
      - 66
      - 213
      - 208
      - 129
      - 18
      - 228
      - 8
      - 217
      - 188
      - 254
      - 180
      - 108
      - 214
      - 82
      - 196
      - 2
      - 131
      - 159
      - 180
      - 14
      - 132
      - 103
      - 144
      - 150
      - 174
      - 15
  faucet_pk: d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916
time:
  slot_duration: '1.000000000'
  chain_start_time: 2026-04-15 20:50:27.96275 +00:00:00
mempool:
  pubsub_topic: /logos-blockchain-devnet/mempool/1.0.0
