blend:
  common:
    num_blend_layers: 1
    minimum_network_size: 32
    protocol_name: /logos-blockchain-devnet/blend/1.0.0
    data_replication_factor: 0
  core:
    scheduler:
      cover:
        message_frequency_per_round: 1.0
        intervals_for_safety_buffer: 100
      delayer:
        maximum_release_delay_in_rounds: 1
    minimum_messages_coefficient: 1
    normalization_constant: 1.03
    activity_threshold_sensitivity: 1
network:
  kademlia_protocol_name: /logos-blockchain-devnet/kad/1.0.0
  identify_protocol_name: /logos-blockchain-devnet/identify/1.0.0
  chain_sync_protocol_name: /logos-blockchain-devnet/chainsync/1.0.0
cryptarchia:
  epoch_config:
    epoch_stake_distribution_stabilization: 3
    epoch_period_nonce_buffer: 3
    epoch_period_nonce_stabilization: 4
  security_param: 30
  slot_activation_coeff:
    numerator: 1
    denominator: 20
  learning_rate: 0.5
  sdp_config:
    service_params:
      BN:
        lock_period: 10
        inactivity_period: 1
        retention_period: 1
        timestamp: 0
    min_stake:
      threshold: 1
      timestamp: 0
  gossipsub_protocol: /logos-blockchain-devnet/cryptarchia/1.0.0
  genesis_state:
    mantle_tx:
      ops:
      - opcode: 0
        payload:
          inputs: []
          outputs:
          - value: 100000
            pk: 023301b903fa7173637dffe490d643aa5fd7c6ad42e696253a91921b5f93b11e
          - value: 1
            pk: 95182026c229fa03adb5bbacd859c3e512f34284ef1db8100b272159eb557029
          - value: 100
            pk: 57fd3cf9abdcc87ee95a951f0ebb3604cd4dd787d74de844e7adf686099eee15
          - value: 100000
            pk: b1299b28da709a5a422fd9157bfbe0924031a509d440c102b7d44dd46302f40a
          - value: 1
            pk: 9574ac2426e666177653ed54f14ca8d4e09e6ccc386a503dc6da4e090c4f7d1d
          - value: 100
            pk: cbc8cb3fcef3b77fe5569da6b98ac39ed2fceebc27871879268e303cb854ad0a
          - value: 100000
            pk: 4acffec29e556d862d1dada437616e1da81b8e9961b75fe43c2759682477400d
          - value: 1
            pk: 4b8cce7433aa3e2ba7e7896aefb929f2ae5b5686452aa39a029187f63c6d2314
          - value: 100
            pk: 77a4f68356b3849998966742c179acccc2e25c74958756c95680bc2951a9c310
          - value: 100000
            pk: 799352fec1bb5d32de7f3e3e89d01abc771a1a684eaf1f9bda7dfdf672fcec03
          - value: 1
            pk: 616653275260697c5e7b488b566977e181b1441f06c60fc630efdd17fb756424
          - value: 100
            pk: 9afff465c819ce3510b3db3c0cbee7fad168e7f94433813e8d5b452b75af441c
          - value: 18446744073709151211
            pk: d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916
      - opcode: 17
        payload:
          channel_id: '0000000000000000000000000000000000000000000000000000000000000000'
          inscription:
          - 103
          - 101
          - 110
          - 101
          - 115
          - 105
          - 115
          parent: '0000000000000000000000000000000000000000000000000000000000000000'
          signer: '0000000000000000000000000000000000000000000000000000000000000000'
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /ip4/127.0.0.0/udp/3400/quic-v1
          provider_id: 4cb4cab9cdc46dd5a7ad3966570505ba5c61aa943a763632b632e14c93aeefb3
          zk_id: efaebbcee3b487cf152cc20625e0c1fe61667113914323793a3e99bf54e1d80c
          locked_note_id: af5d3605c67ccdb2a5d6bc79b247ad5d96f2a797c31d974d01c401d38d40e518
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /ip4/127.0.0.1/udp/3400/quic-v1
          provider_id: 168773da0fcf68c7921657ad4158cc24fb18fe98dc07e66e03422fbae3d63f16
          zk_id: efb0644826540fb81383e488f3b3de1a885bcb545a61743bbcccdf02df7a162b
          locked_note_id: 225a905bbacbb8eb92b4efe94909744fc6b4ea9e77613ee24373bbea5df7180c
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /ip4/127.0.0.2/udp/3400/quic-v1
          provider_id: 395a43ff4d805c8f25d154dee2f5526e85be6352b5436e3689d9092fd1f346d7
          zk_id: 2285537a2ab31794caa54193eb845269722e394bb0255e5b836705a2690c3b0f
          locked_note_id: 5abb9cfcd15e87dc89b784a4580a833859ecd58e2c6a1aff24285083b0ebfe2c
      - opcode: 32
        payload:
          service_type: BN
          locators:
          - /ip4/127.0.0.3/udp/3400/quic-v1
          provider_id: a11d39b038b61382db01a72f5a5c34a3f2cfe775857eba7e68e069dbb7db0bf1
          zk_id: 782ba296b82086fa8f221d40c5471cf2563edbda1345fa259a04ee478bf0701f
          locked_note_id: 64b5054e19097088d036dad580361f1a016552dc5920894976ec0731fcf8ed27
      execution_gas_price: 0
      storage_gas_price: 0
    ops_proofs:
    - !ZkSig
      pi_a:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      pi_b:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      pi_c:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    - NoProof
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 37
        - 107
        - 13
        - 86
        - 158
        - 172
        - 72
        - 10
        - 94
        - 231
        - 209
        - 19
        - 216
        - 205
        - 246
        - 96
        - 238
        - 192
        - 90
        - 183
        - 232
        - 14
        - 190
        - 78
        - 89
        - 22
        - 246
        - 184
        - 122
        - 122
        - 183
        - 19
        pi_b:
        - 244
        - 248
        - 0
        - 39
        - 40
        - 237
        - 132
        - 215
        - 236
        - 191
        - 93
        - 142
        - 26
        - 149
        - 48
        - 128
        - 81
        - 40
        - 228
        - 122
        - 242
        - 18
        - 131
        - 84
        - 178
        - 76
        - 239
        - 57
        - 6
        - 246
        - 46
        - 29
        - 41
        - 105
        - 80
        - 149
        - 249
        - 212
        - 33
        - 81
        - 90
        - 31
        - 210
        - 43
        - 73
        - 171
        - 9
        - 154
        - 29
        - 205
        - 55
        - 53
        - 109
        - 104
        - 213
        - 184
        - 27
        - 6
        - 197
        - 120
        - 129
        - 59
        - 156
        - 128
        pi_c:
        - 196
        - 54
        - 223
        - 30
        - 207
        - 181
        - 37
        - 66
        - 102
        - 172
        - 24
        - 27
        - 61
        - 109
        - 160
        - 246
        - 6
        - 51
        - 20
        - 168
        - 158
        - 53
        - 66
        - 213
        - 15
        - 177
        - 194
        - 40
        - 69
        - 127
        - 222
        - 134
      ed25519_sig:
      - 34
      - 183
      - 241
      - 175
      - 83
      - 77
      - 198
      - 32
      - 78
      - 250
      - 184
      - 101
      - 247
      - 60
      - 201
      - 175
      - 172
      - 28
      - 66
      - 242
      - 113
      - 142
      - 142
      - 123
      - 113
      - 71
      - 56
      - 252
      - 64
      - 231
      - 66
      - 31
      - 90
      - 36
      - 104
      - 132
      - 215
      - 186
      - 48
      - 185
      - 118
      - 85
      - 171
      - 234
      - 124
      - 38
      - 200
      - 239
      - 173
      - 196
      - 216
      - 197
      - 213
      - 112
      - 173
      - 185
      - 19
      - 169
      - 208
      - 185
      - 61
      - 22
      - 246
      - 15
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 253
        - 241
        - 26
        - 0
        - 252
        - 164
        - 117
        - 225
        - 218
        - 79
        - 30
        - 5
        - 34
        - 198
        - 15
        - 188
        - 67
        - 233
        - 202
        - 100
        - 63
        - 5
        - 205
        - 210
        - 106
        - 207
        - 71
        - 74
        - 52
        - 22
        - 119
        - 166
        pi_b:
        - 14
        - 57
        - 203
        - 154
        - 158
        - 245
        - 217
        - 23
        - 70
        - 108
        - 113
        - 162
        - 209
        - 126
        - 249
        - 100
        - 174
        - 113
        - 43
        - 51
        - 202
        - 46
        - 15
        - 167
        - 61
        - 36
        - 153
        - 48
        - 27
        - 67
        - 2
        - 37
        - 151
        - 176
        - 117
        - 141
        - 26
        - 100
        - 183
        - 32
        - 41
        - 146
        - 175
        - 202
        - 157
        - 106
        - 197
        - 200
        - 108
        - 247
        - 43
        - 88
        - 63
        - 209
        - 59
        - 186
        - 87
        - 11
        - 51
        - 59
        - 145
        - 178
        - 93
        - 156
        pi_c:
        - 226
        - 116
        - 89
        - 254
        - 89
        - 46
        - 86
        - 66
        - 236
        - 113
        - 219
        - 98
        - 167
        - 223
        - 162
        - 207
        - 147
        - 170
        - 20
        - 134
        - 18
        - 128
        - 151
        - 93
        - 164
        - 40
        - 99
        - 73
        - 233
        - 239
        - 170
        - 157
      ed25519_sig:
      - 72
      - 186
      - 30
      - 71
      - 22
      - 94
      - 155
      - 233
      - 138
      - 214
      - 93
      - 168
      - 151
      - 234
      - 27
      - 219
      - 243
      - 44
      - 65
      - 137
      - 140
      - 226
      - 73
      - 129
      - 10
      - 101
      - 159
      - 45
      - 129
      - 6
      - 65
      - 171
      - 214
      - 147
      - 234
      - 193
      - 13
      - 218
      - 229
      - 199
      - 144
      - 221
      - 199
      - 21
      - 133
      - 180
      - 126
      - 149
      - 8
      - 101
      - 83
      - 61
      - 110
      - 88
      - 53
      - 165
      - 214
      - 107
      - 18
      - 158
      - 178
      - 14
      - 190
      - 13
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 173
        - 235
        - 15
        - 189
        - 53
        - 165
        - 66
        - 18
        - 216
        - 190
        - 103
        - 10
        - 209
        - 214
        - 133
        - 174
        - 127
        - 126
        - 223
        - 137
        - 103
        - 85
        - 169
        - 80
        - 49
        - 93
        - 56
        - 148
        - 206
        - 10
        - 145
        - 11
        pi_b:
        - 56
        - 51
        - 231
        - 148
        - 55
        - 127
        - 78
        - 181
        - 246
        - 228
        - 24
        - 28
        - 4
        - 178
        - 229
        - 3
        - 86
        - 24
        - 8
        - 73
        - 167
        - 159
        - 152
        - 253
        - 169
        - 0
        - 234
        - 109
        - 26
        - 224
        - 194
        - 45
        - 64
        - 25
        - 246
        - 117
        - 51
        - 132
        - 231
        - 220
        - 244
        - 191
        - 14
        - 209
        - 50
        - 191
        - 215
        - 40
        - 109
        - 120
        - 47
        - 104
        - 194
        - 49
        - 210
        - 205
        - 55
        - 96
        - 6
        - 118
        - 158
        - 9
        - 253
        - 18
        pi_c:
        - 17
        - 207
        - 202
        - 228
        - 236
        - 203
        - 234
        - 5
        - 6
        - 215
        - 183
        - 160
        - 225
        - 101
        - 210
        - 246
        - 68
        - 70
        - 172
        - 19
        - 16
        - 194
        - 111
        - 26
        - 220
        - 153
        - 241
        - 230
        - 104
        - 87
        - 102
        - 39
      ed25519_sig:
      - 193
      - 196
      - 156
      - 163
      - 242
      - 44
      - 186
      - 11
      - 158
      - 6
      - 39
      - 54
      - 157
      - 77
      - 135
      - 165
      - 201
      - 143
      - 85
      - 241
      - 47
      - 166
      - 53
      - 66
      - 129
      - 179
      - 177
      - 37
      - 106
      - 181
      - 71
      - 29
      - 227
      - 131
      - 196
      - 62
      - 165
      - 193
      - 0
      - 61
      - 171
      - 112
      - 16
      - 92
      - 33
      - 18
      - 143
      - 106
      - 65
      - 234
      - 54
      - 215
      - 78
      - 155
      - 69
      - 252
      - 201
      - 237
      - 92
      - 86
      - 227
      - 104
      - 47
      - 4
    - !ZkAndEd25519Sigs
      zk_sig:
        pi_a:
        - 231
        - 252
        - 5
        - 253
        - 144
        - 1
        - 214
        - 25
        - 238
        - 131
        - 205
        - 58
        - 142
        - 196
        - 97
        - 54
        - 186
        - 32
        - 239
        - 25
        - 128
        - 122
        - 241
        - 172
        - 18
        - 59
        - 62
        - 150
        - 94
        - 56
        - 178
        - 20
        pi_b:
        - 121
        - 217
        - 166
        - 60
        - 106
        - 184
        - 8
        - 255
        - 230
        - 150
        - 40
        - 81
        - 56
        - 222
        - 204
        - 231
        - 207
        - 37
        - 66
        - 255
        - 174
        - 227
        - 214
        - 49
        - 151
        - 123
        - 67
        - 135
        - 164
        - 222
        - 144
        - 0
        - 19
        - 29
        - 65
        - 26
        - 38
        - 184
        - 23
        - 150
        - 190
        - 138
        - 9
        - 217
        - 146
        - 124
        - 230
        - 177
        - 153
        - 111
        - 98
        - 78
        - 132
        - 110
        - 148
        - 7
        - 54
        - 27
        - 73
        - 83
        - 187
        - 224
        - 30
        - 150
        pi_c:
        - 168
        - 251
        - 180
        - 118
        - 82
        - 76
        - 70
        - 159
        - 195
        - 10
        - 4
        - 212
        - 54
        - 65
        - 94
        - 129
        - 141
        - 246
        - 26
        - 62
        - 221
        - 153
        - 92
        - 7
        - 237
        - 38
        - 226
        - 173
        - 219
        - 119
        - 12
        - 140
      ed25519_sig:
      - 227
      - 2
      - 206
      - 50
      - 102
      - 66
      - 11
      - 174
      - 93
      - 158
      - 26
      - 99
      - 133
      - 58
      - 147
      - 150
      - 183
      - 64
      - 64
      - 194
      - 7
      - 169
      - 86
      - 199
      - 103
      - 90
      - 124
      - 116
      - 174
      - 232
      - 7
      - 172
      - 224
      - 38
      - 115
      - 248
      - 148
      - 55
      - 127
      - 54
      - 71
      - 57
      - 41
      - 66
      - 190
      - 193
      - 172
      - 229
      - 77
      - 169
      - 217
      - 224
      - 252
      - 202
      - 207
      - 30
      - 138
      - 227
      - 61
      - 13
      - 20
      - 149
      - 18
      - 14
  faucet_pk: d731e00126f55e9ecfb1d1bd47e599c2728e347f4a865449e133db5486233916
time:
  slot_duration: '1.000000000'
  chain_start_time: 2026-03-25 13:40:49.651595868 +00:00:00
mempool:
  pubsub_topic: /logos-blockchain-devnet/mempool/1.0.0
