use lb_groth16::{Fr, fr_to_bytes};
use lb_poseidon2::{Digest as _, Poseidon2Bn254Hasher};

use crate::hd::{ExtendedSecretKey, HardenedIndex, HardenedIndexError, ZK_KEY_DST};

const SEED: &str = "000102030405060708090a0b0c0d0e0f";

// Reference values computed from `SEED` with Python `hashlib.blake2b`
const MASTER_KEY: &str = "3df9737d9420e444bd2089774bf02a0c8da16e12a8c4f1ea8d27a29cc91aa7db";
const MASTER_CHAIN_CODE: &str = "98cb25a48650ea3f8fcb2d856ec5b5b452b43916c1db711ed924205c3d679072";
const CHILD_0_KEY: &str = "8d560e6d8e8803012caf9fa908bf70d271ccb7aedb8691a9b1163f9e80d2081d";
const CHILD_0_CHAIN_CODE: &str = "7164377df731d20d2dd6f55d34826ac7e99f9bb2b867cec9b9a3f79dbd13fc87";
const CHILD_0_1_KEY: &str = "b6e0b0893f45c6d6ef7396cb0817d57ffc66f03d83b07ccaad8e3949968428f5";
const CHILD_0_1_CHAIN_CODE: &str =
    "5751a5b756cf811e715af61ed891dde2057e7e333a401c8a5b214077a636a09c";

// Generated by this module. Replace this when the spec changes.
const MASTER_ZK_KEY: &str = "4352f57de9d95c233a51511994c8361999fcf773802d9585dce8f05eb3b18b1a";

#[test]
fn master_key_generation() {
    let master = master();
    assert_eq!(hex::encode(master.key), MASTER_KEY);
    assert_eq!(hex::encode(master.chain_code), MASTER_CHAIN_CODE);
}

#[test]
fn child_key_derivation() {
    let child = master().derive_child(index(0));
    assert_eq!(hex::encode(child.key), CHILD_0_KEY);
    assert_eq!(hex::encode(child.chain_code), CHILD_0_CHAIN_CODE);
}

#[test]
fn child_key_derivation_from_path() {
    let derived = master().derive_path(&[index(0), index(1)]);
    assert_eq!(hex::encode(derived.key), CHILD_0_1_KEY);
    assert_eq!(hex::encode(derived.chain_code), CHILD_0_1_CHAIN_CODE);
}

#[test]
fn empty_path_returns_same_key() {
    let master = master();
    let derived = master.derive_path(&[]);
    assert_eq!(derived.key, master.key);
    assert_eq!(derived.chain_code, master.chain_code);
}

#[test]
fn different_indices_derive_different_keys() {
    let master = master();
    assert_ne!(
        master.derive_child(index(0)).key,
        master.derive_child(index(1)).key
    );
}

#[test]
fn chain_code_affects_child_key() {
    let master = master();
    let other = ExtendedSecretKey {
        key: master.key,
        chain_code: [0u8; 32],
    };
    assert_ne!(
        master.derive_child(index(0)).key,
        other.derive_child(index(0)).key
    );
}

#[test]
fn zk_key_derived_from_extended_secret_key() {
    assert_eq!(
        hex::encode(fr_to_bytes(master().to_zk_key().as_fr())),
        MASTER_ZK_KEY
    );
}

#[test]
fn zk_key_hashes_little_endian_halves_with_dst() {
    let mut key = [0u8; 32];
    key[0] = 1;
    key[16] = 2;
    let extended = ExtendedSecretKey {
        key,
        chain_code: [0u8; 32],
    };
    let expected = Poseidon2Bn254Hasher::digest(&[
        *ZK_KEY_DST,
        // The left half `01 00 .. 00` (little-endian) is 1.
        Fr::from(1u64),
        // The right half `02 00 .. 00` (little-endian) is 2.
        Fr::from(2u64),
    ]);
    assert_eq!(*extended.to_zk_key().as_fr(), expected);
}

#[test]
fn hardened_index_adds_offset() {
    assert_eq!(index(0).0, HardenedIndex::OFFSET);
    assert_eq!(index(HardenedIndex::OFFSET - 1).0, u32::MAX);
}

#[test]
fn hardened_index_serializes_big_endian() {
    assert_eq!(index(0).to_be_bytes(), [0x80, 0x00, 0x00, 0x00]);
}

#[test]
fn hardened_index_rejects_large_child_number() {
    assert_eq!(
        HardenedIndex::new(HardenedIndex::OFFSET),
        Err(HardenedIndexError::ChildNumberTooLarge(
            HardenedIndex::OFFSET
        ))
    );
}

fn master() -> ExtendedSecretKey {
    ExtendedSecretKey::from_seed(&hex::decode(SEED).unwrap())
}

fn index(number: u32) -> HardenedIndex {
    HardenedIndex::new(number).unwrap()
}
