use lb_groth16::{Fr, fr_to_bytes};
use lb_poseidon2::{Digest as _, Poseidon2Bn254Hasher};

use crate::hd::{ExtendedSecretKey, HardenedIndex, MasterSeed, ZK_KEY_DST, u31};

const SEED: &str = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f";

// Reference values computed from `SEED` with Python `hashlib.blake2b`
const MASTER_KEY: &str = "496c4ed8388182fcb4cccd460b44131e2fff8f9558375e63e8e2f479d6a51ff9";
const MASTER_CHAIN_CODE: &str = "79900c9b21d4c04d0b3c9cea1b1272f096e814dcd82fe7a6ac8db476cba3fae1";
const CHILD_0_KEY: &str = "0cc7d747281f4637bca710ee6079ad1749aede89faee292efd90639bae231a45";
const CHILD_0_CHAIN_CODE: &str = "92d399f4476d16ee04a9d9f04c0ce11ea4e931e08b6055d5e2ba1e1cd9e43f97";
const CHILD_0_1_KEY: &str = "40ee2565d7a9f892c4687f54ea6a16dab006abbb8d3fca8f917efae3c1656ee2";
const CHILD_0_1_CHAIN_CODE: &str =
    "b588bf671a07e6f24084953a0b04d9bf908e8f2d1d375f92548d085a28094ab5";

// Generated by this module. Replace this when the spec changes.
const MASTER_ZK_KEY: &str = "a6d57088c71de6add33dc3675f087ae4b6671bf93d819c67b08df6f70c244c25";

#[test]
fn master_key_generation() {
    let master = master();
    assert_eq!(hex::encode(master.key), MASTER_KEY);
    assert_eq!(hex::encode(master.chain_code), MASTER_CHAIN_CODE);
}

#[test]
fn child_key_derivation() {
    let child = master().derive_child(index(0));
    assert_eq!(hex::encode(child.key), CHILD_0_KEY);
    assert_eq!(hex::encode(child.chain_code), CHILD_0_CHAIN_CODE);
}

#[test]
fn child_key_derivation_from_path() {
    let derived = master().derive_path(&[index(0), index(1)]);
    assert_eq!(hex::encode(derived.key), CHILD_0_1_KEY);
    assert_eq!(hex::encode(derived.chain_code), CHILD_0_1_CHAIN_CODE);
}

#[test]
fn empty_path_returns_same_key() {
    let master = master();
    let derived = master.derive_path(&[]);
    assert_eq!(derived.key, master.key);
    assert_eq!(derived.chain_code, master.chain_code);
}

#[test]
fn different_indices_derive_different_keys() {
    let master = master();
    assert_ne!(
        master.derive_child(index(0)).key,
        master.derive_child(index(1)).key
    );
}

#[test]
fn chain_code_affects_child_key() {
    let master = master();
    let other = ExtendedSecretKey {
        key: master.key,
        chain_code: [0u8; 32],
    };
    assert_ne!(
        master.derive_child(index(0)).key,
        other.derive_child(index(0)).key
    );
}

#[test]
fn zk_key_derived_from_extended_secret_key() {
    assert_eq!(
        hex::encode(fr_to_bytes(master().to_zk_key().as_fr())),
        MASTER_ZK_KEY
    );
}

#[test]
fn zk_key_hashes_little_endian_halves_with_dst() {
    let mut key = [0u8; 32];
    key[0] = 1;
    key[16] = 2;
    let extended = ExtendedSecretKey {
        key,
        chain_code: [0u8; 32],
    };
    let expected = Poseidon2Bn254Hasher::digest(&[
        *ZK_KEY_DST,
        // The left half `01 00 .. 00` (little-endian) is 1.
        Fr::from(1u64),
        // The right half `02 00 .. 00` (little-endian) is 2.
        Fr::from(2u64),
    ]);
    assert_eq!(*extended.to_zk_key().as_fr(), expected);
}

#[test]
fn hardened_index_adds_offset() {
    assert_eq!(index(0).0, HardenedIndex::OFFSET);
    assert_eq!(index(HardenedIndex::OFFSET - 1).0, u32::MAX);
}

#[test]
fn hardened_index_serializes_big_endian() {
    assert_eq!(index(0).to_be_bytes(), [0x80, 0x00, 0x00, 0x00]);
}

fn master() -> ExtendedSecretKey {
    ExtendedSecretKey::from_seed(&MasterSeed(hex::decode(SEED).unwrap().try_into().unwrap()))
}

fn index(number: u32) -> HardenedIndex {
    HardenedIndex::new(u31::new(number))
}
