[package]
description          = "Nimbos adapter for blockchain tests"
edition.workspace    = true
license.workspace    = true
name                 = "blockchain-test-nimbos"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
async-trait                    = { workspace = true }
blockchain-test-support        = { workspace = true }
libp2p                         = { features = ["ed25519"], workspace = true }
multiaddr                      = { workspace = true }
serde                          = { features = ["derive"], workspace = true }
serde_yaml                     = { workspace = true }
testing-framework-core         = { workspace = true }
testing-framework-runner-local = { workspace = true }
toml                           = { features = ["display", "parse", "serde", "std"], workspace = true }
url                            = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio    = { features = ["macros", "rt-multi-thread"], workspace = true }
