[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "logos-blockchain-da-sampling-service"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[lints]
workspace = true

[dependencies]
async-trait                               = "0.1"
bytes                                     = { workspace = true }
either                                    = { default-features = false, version = "1.15.0" }
futures                                   = { default-features = false, version = "0.3" }
hex                                       = { default-features = false, version = "0.4.3" }
libp2p-identity                           = { version = "0.2" }
logos-blockchain-core                     = { workspace = true }
logos-blockchain-da-network-core          = { workspace = true }
logos-blockchain-da-network-service       = { workspace = true }
logos-blockchain-kzgrs-backend            = { workspace = true }
logos-blockchain-services-utils           = { workspace = true }
logos-blockchain-storage-service          = { workspace = true }
logos-blockchain-subnetworks-assignations = { workspace = true }
logos-blockchain-tracing                  = { workspace = true }
logos-blockchain-tx-service               = { workspace = true }
overwatch                                 = { workspace = true }
rand                                      = { workspace = true }
serde                                     = { workspace = true }
thiserror                                 = "1.0"
tokio                                     = { default-features = false, features = ["test-util"], version = "1" }
tokio-stream                              = { default-features = false, version = "0.1.15" }
tracing                                   = { workspace = true }

[dev-dependencies]
logos-blockchain-kzgrs = { workspace = true }

[features]
default         = ["libp2p"]
libp2p          = []
rocksdb-backend = ["logos-blockchain-storage-service/rocksdb-backend"]
