[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "logos-blockchain-poc"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[dependencies]
logos-blockchain-circuits-prover   = { workspace = true }
logos-blockchain-circuits-utils    = { workspace = true }
logos-blockchain-groth16           = { features = ["deser"], workspace = true }
logos-blockchain-witness-generator = { workspace = true }
num-bigint                         = "0.4"
serde                              = { features = ["derive", "std"], workspace = true }
serde_json                         = { version = "1.0" }
thiserror                          = "2.0"

[dev-dependencies]

[build-dependencies]
logos-blockchain-circuits-utils = { workspace = true }

[lints]
workspace = true

[features]
build-verification-key = []
default                = ["build-verification-key"]
