use bytes::Bytes;
use serde::{Deserialize, Serialize};

use crate::{
    codec::{DeserializeOp as _, SerializeOp as _},
    crypto::Hash,
    mantle::{
        TxHash, Value,
        ops::channel::{ChannelId, deposit::Metadata},
    },
};

/// Events generated by the execution of block/transaction/operation
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Events(Vec<Event>);

impl Events {
    #[must_use]
    pub const fn new() -> Self {
        Self(Vec::new())
    }

    pub fn extend(&mut self, events: Self) {
        self.0.extend(events.0);
    }

    pub fn iter(&self) -> impl Iterator<Item = &Event> {
        self.0.iter()
    }

    #[must_use]
    pub const fn len(&self) -> usize {
        self.0.len()
    }

    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl FromIterator<Event> for Events {
    fn from_iter<T: IntoIterator<Item = Event>>(iter: T) -> Self {
        Self(iter.into_iter().collect())
    }
}

/// An event generated by the execution of block/transaction/operation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Event {
    Tx {
        tx_hash: TxHash,
        op_id: Hash,
        payload: EventPayload,
    },
    Ledger(EventPayload),
}

impl Event {
    #[must_use]
    pub const fn from_tx(tx_hash: TxHash, op_id: Hash, payload: EventPayload) -> Self {
        Self::Tx {
            tx_hash,
            op_id,
            payload,
        }
    }

    #[must_use]
    pub const fn from_ledger(payload: EventPayload) -> Self {
        Self::Ledger(payload)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum EventPayload {
    Deposit {
        channel_id: ChannelId,
        amount: Value,
        metadata: Metadata,
    },
}

impl TryFrom<Bytes> for Events {
    type Error = crate::codec::Error;

    fn try_from(bytes: Bytes) -> Result<Self, Self::Error> {
        Self::from_bytes(&bytes)
    }
}

impl TryFrom<Events> for Bytes {
    type Error = crate::codec::Error;

    fn try_from(events: Events) -> Result<Self, Self::Error> {
        events.to_bytes()
    }
}
