use bytes::Bytes;
use lb_key_management_system_keys::keys::ZkPublicKey;
use lb_utils::bounded::UpperBoundedVec;
use serde::{Deserialize, Serialize};

use crate::{
    codec::{DeserializeOp as _, SerializeOp as _},
    crypto::Hash,
    mantle::{
        NoteId, Utxo, Value,
        ledger::MAX_TRANSACTION_INPUTS,
        ops::{
            channel::{ChannelId, deposit::Metadata},
            leader_claim::VoucherNullifier,
            pow::PowNullifier,
        },
        transactions::hash::TxHash,
    },
    sdp::{DeclarationId, ServiceType},
};

/// Events generated by the execution of block/transaction/operation
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Events(Vec<Event>);

impl Events {
    #[must_use]
    pub const fn new() -> Self {
        Self(Vec::new())
    }

    pub fn extend(&mut self, events: Self) {
        self.0.extend(events.0);
    }

    pub fn iter(&self) -> impl Iterator<Item = &Event> {
        self.0.iter()
    }

    #[must_use]
    pub const fn len(&self) -> usize {
        self.0.len()
    }

    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl FromIterator<Event> for Events {
    fn from_iter<T: IntoIterator<Item = Event>>(iter: T) -> Self {
        Self(iter.into_iter().collect())
    }
}

impl From<Event> for Events {
    fn from(event: Event) -> Self {
        Self(vec![event])
    }
}

/// An event generated by the execution of block/transaction/operation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Event {
    /// Emitted while processing a block header
    Header(HeaderEvent),
    /// Emitted while processing a transaction
    Tx(TxEvent),
}

impl From<TxEvent> for Event {
    fn from(event: TxEvent) -> Self {
        Self::Tx(event)
    }
}

impl From<HeaderEvent> for Event {
    fn from(event: HeaderEvent) -> Self {
        Self::Header(event)
    }
}

/// An event emitted while processing a transaction
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TxEvent {
    pub tx_hash: TxHash,
    pub op_id: Hash,
    pub payload: TxEventPayload,
}

impl TxEvent {
    #[must_use]
    pub const fn new(tx_hash: TxHash, op_id: Hash, payload: TxEventPayload) -> Self {
        Self {
            tx_hash,
            op_id,
            payload,
        }
    }
}

/// A single channel note a deposit re-created from one of its inputs.
///
/// Carries the data a wallet needs to track and later select the note: its id,
/// value, and owning public key. The public key is the depositor's — a deposit
/// re-creates each input note unchanged inside the channel — so a withdrawal
/// client can tell which key must authorize spending it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct DepositNote {
    pub note_id: NoteId,
    pub value: Value,
    pub pk: ZkPublicKey,
}

// A deposit re-creates one channel note per input, so the notes it emits carry
// the same bound as its inputs.
pub type DepositRecreatedNotes = UpperBoundedVec<DepositNote, MAX_TRANSACTION_INPUTS>;

/// Event payloads emitted while processing a transaction
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TxEventPayload {
    Deposit {
        channel_id: ChannelId,
        amount: Value,
        metadata: Metadata,
        /// The channel notes the deposit re-created its inputs as. They carry
        /// new `NoteId`s, so a channel cannot derive them from the payload.
        notes: DepositRecreatedNotes,
    },
    /// A leader claim operation created the reward note for its beneficiary.
    LeaderRewardClaimed {
        voucher_nullifier: VoucherNullifier,
        utxo: Utxo,
    },
    /// A `PoW` claim operation created a reward note for its beneficiary
    PoWRewardClaimed {
        pow_nullifier: PowNullifier,
        utxo: Utxo,
    },
}

/// Events emitted while processing a block header
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum HeaderEvent {
    /// An SDP-locked note has been unlocked because its declaration's
    /// `withdraw_at` epoch has been reached.
    SdpNoteUnlocked {
        note_id: NoteId,
        service_type: ServiceType,
        declaration_id: DeclarationId,
    },
    /// A reward UTXO was minted to a provider.
    SdpRewardDistributed {
        service_type: ServiceType,
        utxo: Utxo,
    },
}

impl TryFrom<Bytes> for Events {
    type Error = crate::codec::Error;

    fn try_from(bytes: Bytes) -> Result<Self, Self::Error> {
        Self::from_bytes(&bytes)
    }
}

impl TryFrom<Events> for Bytes {
    type Error = crate::codec::Error;

    fn try_from(events: Events) -> Result<Self, Self::Error> {
        events.to_bytes()
    }
}

#[cfg(test)]
mod tests {
    use lb_groth16::Fr;
    use num_bigint::BigUint;

    use super::*;

    /// A deposit note with distinct, non-default id/value/pk so the round-trip
    /// exercises every field rather than zero-valued defaults.
    fn deposit_note(seed: u64, value: Value) -> DepositNote {
        DepositNote {
            note_id: NoteId::from(Fr::from(BigUint::from(seed))),
            value,
            pk: ZkPublicKey::from(Fr::from(BigUint::from(
                seed.wrapping_mul(97).wrapping_add(3),
            ))),
        }
    }

    /// A `Deposit` payload carrying several notes must survive the events codec
    /// round-trip. The wallet reads these notes off the block-events endpoint,
    /// so a broken `DepositNote` (de)serialization would silently drop the
    /// per-note value/pk data that channel-note tracking depends on.
    #[test]
    fn deposit_event_notes_survive_codec_round_trip() {
        let expected_notes = vec![
            deposit_note(11, 1),
            deposit_note(22, 10_000),
            deposit_note(33, u64::MAX),
        ];
        let notes: DepositRecreatedNotes = expected_notes
            .clone()
            .try_into()
            .expect("note count is within the input bound");

        let tx_hash = TxHash([1u8; 32]);
        let op_id: Hash = [2u8; 32];
        let channel_id = ChannelId::from([7u8; 32]);
        let amount: Value = 424_242;
        let metadata: Metadata = vec![9u8, 8, 7]
            .try_into()
            .expect("metadata is within the size bound");

        let events = Events::from(Event::Tx(TxEvent::new(
            tx_hash,
            op_id,
            TxEventPayload::Deposit {
                channel_id,
                amount,
                metadata: metadata.clone(),
                notes,
            },
        )));

        let bytes: Bytes = events.try_into().expect("events serialize");
        let decoded = Events::try_from(bytes).expect("events deserialize");

        let mut iter = decoded.iter();
        let event = iter.next().expect("one event round-trips");
        assert!(iter.next().is_none(), "exactly one event round-trips");

        let Event::Tx(TxEvent {
            tx_hash: decoded_tx_hash,
            op_id: decoded_op_id,
            payload:
                TxEventPayload::Deposit {
                    channel_id: decoded_channel_id,
                    amount: decoded_amount,
                    metadata: decoded_metadata,
                    notes: decoded_notes,
                },
        }) = event
        else {
            panic!("expected a deposit Tx event, got {event:?}");
        };

        assert_eq!(*decoded_tx_hash, tx_hash);
        assert_eq!(*decoded_op_id, op_id);
        assert_eq!(*decoded_channel_id, channel_id);
        assert_eq!(*decoded_amount, amount);
        assert_eq!(decoded_metadata.as_slice(), metadata.as_slice());
        assert_eq!(decoded_notes.as_slice(), expected_notes.as_slice());
    }
}
