[package]
categories  = { workspace = true }
description = { workspace = true }
edition     = { workspace = true }
keywords    = { workspace = true }
license     = { workspace = true }
name        = "chain-network"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[lints]
workspace = true

[dependencies]
async-trait                  = "0.1"
chain-common                 = { workspace = true }
chain-service                = { workspace = true }
cryptarchia-engine           = { features = ["serde"], workspace = true }
cryptarchia-sync             = { workspace = true }
futures                      = { default-features = false, version = "0.3" }
logos-blockchain-core        = { workspace = true }
logos-blockchain-da-sampling = { workspace = true }
logos-blockchain-ledger      = { features = ["serde"], workspace = true }
logos-blockchain-network     = { workspace = true }
logos-blockchain-time        = { workspace = true }
overwatch                    = { workspace = true }
rand                         = { default-features = false, version = "0.8" }
serde                        = { default-features = false, version = "1" }
serde_with                   = { workspace = true }
services-utils               = { workspace = true }
thiserror                    = "1.0"
tokio                        = { default-features = false, version = "1" }
tokio-stream                 = { default-features = false, version = "0.1" }
tracing                      = { workspace = true }
tracing-futures              = { default-features = false, version = "0.2" }
tx-service                   = { workspace = true }

[dev-dependencies]
logos-blockchain-core    = { features = ["mock"], workspace = true }
logos-blockchain-network = { features = ["mock"], workspace = true }
logos-blockchain-utils   = { workspace = true }

[features]
default      = []
libp2p       = ["logos-blockchain-network/libp2p"]
pol-dev-mode = ["logos-blockchain-core/pol-dev-mode"]
