[package]
name = "dynamic-merkle"
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, features = ["alloc", "derive", "rc"] }
rpds = { workspace = true, features = ["serde"] }

[dev-dependencies]
ark-ff       = { workspace = true }
lb-poseidon2 = { workspace = true }
num-bigint   = { workspace = true }
rand         = { workspace = true }

[lints]
workspace = true
