name: Logos Genesis Ceremony workflow

on:
  workflow_dispatch:
    inputs:
      deployment:
        description: "Target deployment environment (e.g., devnet, testnet)"
        required: true
        default: "devnet"
      version:
        description: "Protocol version string"
        required: true
        default: "X.Y.Z-rc.0"

jobs:
  genesis-ceremony:
    name: Genesis Ceremony
    runs-on: ubuntu-24.04
    env:
      LB_TARGET_ENV: ${{ github.event.inputs.deployment }}
      LB_VERSION: ${{ github.event.inputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2

      - name: Setup Circuits
        uses: ./.github/actions/setup-circuits
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Inject Variables into Template
        run: |
          cp testnet/ceremony/genesis/$LB_TARGET_ENV/deployment-template.yaml \
            /tmp/deployment-generated.yaml

          # We use '|' as a delimiter so that slashes in paths don't break the command
          sed -i "s|ENV_PLACEHOLDER|$LB_TARGET_ENV|g" /tmp/deployment-generated.yaml
          sed -i "s|VERSION_PLACEHOLDER|$LB_VERSION|g" /tmp/deployment-generated.yaml

      - name: Run Ceremony
        run: |
          cargo run --locked --bin logos-blockchain-tools-genesis -- ceremony \
            --inscription-params testnet/ceremony/genesis/$LB_TARGET_ENV/inscribe.yaml \
            --stake-holders testnet/ceremony/genesis/$LB_TARGET_ENV/stakeholders.yaml \
            --providers testnet/ceremony/genesis/$LB_TARGET_ENV/providers.yaml \
            --deployment /tmp/deployment-generated.yaml \
            --output nodes/node/binary/src/config/deployment/devnet/deployment.yaml

      - name: Commit and Push changes
        run: |
          NEW_BRANCH="genesis-ceremony-$LB_TARGET_ENV-$LB_VERSION"

          # Configure git with a generic bot identity
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git checkout -b $NEW_BRANCH
          git add nodes/node/binary/src/config/deployment/devnet/deployment.yaml

          # Only commit and push if there are actual changes
          if git diff --staged --quiet; then
            echo "Error: No changes detected in deployment.yaml. Genesis ceremony likely produced identical output."
            exit 1
          else
            git commit -m "chore: genesis ceremony for $LB_TARGET_ENV version $LB_VERSION"
            git push -u origin "$NEW_BRANCH"

            PR_URL="${{ github.server_url }}/${{ github.repository }}/pull/new/$NEW_BRANCH"
            echo "### Branch Created Successfully" >> $GITHUB_STEP_SUMMARY
            echo "[Click here to create your Pull Request]($PR_URL)" >> $GITHUB_STEP_SUMMARY
          fi
