name: Prepare release draft with built binaries

on:
  workflow_dispatch:
  push:
    branches:
      - aa/testnet-release-template

jobs:
  setup:
    name: Define variables and configure environment
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.define-version.outputs.version }}
    steps:
      - name: Define version
        id: define-version
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          # if [[ "${{ github.ref_type }}" != "tag" ]]; then
          #   echo "This workflow must be dispatched from a tag, not a branch."
          #   exit 1
          # fi

          # if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          #   echo "VERSION must follow the format of 'X.Y.Z'. Value: '$VERSION'."
          #   exit 2
          # fi

          # echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          echo "version=0.1.0" >> $GITHUB_OUTPUT

  build:
    name: "Build binaries for ${{ matrix.platform.os-display }} (${{ matrix.platform.arch }})"
    needs: setup
    env:
      VERSION: ${{ needs.setup.outputs.version }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: linux
            os-display: Linux
            arch: x86_64
            builder: ubuntu-24.04
            target_triple: x86_64-unknown-linux-gnu
          - os: linux
            os-display: Linux
            arch: aarch64
            builder: ubuntu-24.04
            target_triple: aarch64-unknown-linux-gnu
          - os: macos
            os-display: MacOS
            arch: aarch64
            builder: macos-14
            target_triple: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.builder }}
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2

      - name: Add the target toolchain
        run: rustup target add ${{ matrix.platform.target_triple }}

      - name: Setup Circuits
        uses: ./.github/actions/setup-circuits
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72  # Version 1.0.1
        name: Build node binary
        with:
          command: build
          args: -p logos-blockchain-node --target ${{ matrix.platform.target_triple }}

      - name: Upload binary (${{ matrix.platform.arch }})
        uses: actions/upload-artifact@6027e3dd177782cd8ab9af838c04fd81a07f1d47 # Version 4.6.2
        with:
          name: logos-blockchain-node-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ needs.setup.outputs.version }}
          path: target/${{ matrix.platform.target_triple }}/debug/logos-blockchain-node
          if-no-files-found: error

  create-release:
    name: Create release
    needs:
      - setup
      - build
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.setup.outputs.version }}
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2

      - name: Create Release
        uses: actions/create-release@4c11c9fe1dcd9636620a16455165783b20fc7ea0  # Version 1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Logos Blockchain Node ${{ env.VERSION }}
          body_path: .github/release/release-content.md
          draft: true
          prerelease: true

  upload-artifacts:
    name: Upload Artifacts to release
    needs:
      - setup
      - create-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - os: linux
            arch: x86_64
          - os: linux
            arch: aarch64
          - os: macos
            arch: aarch64

    env:
      UPLOAD_URL: ${{ needs.create-release.outputs.upload_url }}
      BINARY_NAME: logos-blockchain-node-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ needs.setup.outputs.version }}
      DOWNLOAD_DIRECTORY: artifacts
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # Version 4.2.1
        with:
          name: ${{ env.BINARY_NAME }}
          path: ${{ env.DOWNLOAD_DIRECTORY }}
          merge-multiple: true

      - name: Upload ${{ matrix.platform.os }} (${{ matrix.platform.arch }})
        uses: actions/upload-release-asset@ef2adfe8cb8ebfa540930c452c576b3819990faa  # Version 1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ${{ env.DOWNLOAD_DIRECTORY }}/${{ env.BINARY_NAME }}
          asset_name: ${{ env.BINARY_NAME }}
          asset_content_type: application/octet-stream

  upload-user-config:
    name: Upload user config file to release
    needs:
      - create-release
    runs-on: ubuntu-latest
    env:
      UPLOAD_URL: ${{ needs.create-release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2

      - name: Upload user-config.yaml
        uses: actions/upload-release-asset@ef2adfe8cb8ebfa540930c452c576b3819990faa  # Version 1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: nodes/node/config.yaml
          asset_name: user-config.yaml
          asset_content_type: text/yaml