[package]
description          = "Integration runners and adapters for blockchain tests"
edition.workspace    = true
license.workspace    = true
name                 = "blockchain-test-interop"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
async-trait                    = { workspace = true }
lb-testing-framework           = { workspace = true }
libp2p                         = { features = ["ed25519"], workspace = true }
logos-blockchain-tests         = { path = ".." }
multiaddr                      = { workspace = true }
serde                          = { workspace = true }
serde_yaml                     = { workspace = true }
testing-framework-app          = { workspace = true }
testing-framework-core         = { workspace = true }
testing-framework-runner-local = { workspace = true }
tokio                          = { workspace = true }
toml                           = "0.9.12"
url                            = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[[bin]]
name = "cucumber_nimbos"
path = "src/bin/cucumber_nimbos.rs"

[[bin]]
name = "cucumber_external_smoke"
path = "src/bin/cucumber_external_smoke.rs"

[[test]]
name = "logos_nimbos_mixed"
path = "tests/logos_nimbos_mixed.rs"
